meta_product_name: "Tube Stats"
meta_title: "Tube Stats - Track your time, don't waste any more than you need to"
meta_description: "Tube Stats is a service designed to help you make smarter entertainment choices by keeping track of your behavior on YouTube"
meta_image: "app/assets/images/og-image.png"
twitter_account: "@product_twitter_account"   # required for Twitter Cards

